// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/home/lauren/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/home/lauren/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/home/lauren/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/home/lauren/cortextos",
        CTX_PROJECT_ROOT: "/home/lauren/cortextos",
        CTX_ORG: process.env.CTX_ORG || "smoothie-hq",
      },
      max_restarts: 15,
      min_uptime: 10000,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "npm",
      args: "run dev",
      cwd: "/home/lauren/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      max_restarts: 15,
      min_uptime: 10000,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
