import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    cli: 'src/cli/index.ts',
    ascendops: 'src/cli/ascendops.ts',
    daemon: 'src/daemon/index.ts',
    'hooks/hook-permission-telegram': 'src/hooks/hook-permission-telegram.ts',
    'hooks/hook-ask-telegram': 'src/hooks/hook-ask-telegram.ts',
    'hooks/hook-planmode-telegram': 'src/hooks/hook-planmode-telegram.ts',
    'hooks/hook-crash-alert': 'src/hooks/hook-crash-alert.ts',
    'hooks/hook-extract-facts': 'src/hooks/hook-extract-facts.ts',
    'hooks/hook-idle-flag': 'src/hooks/hook-idle-flag.ts',
    'hooks/hook-session-restore': 'src/hooks/hook-session-restore.ts',
    'hooks/hook-loop-detector': 'src/hooks/hook-loop-detector.ts',
    'hooks/hook-skill-autopr': 'src/hooks/hook-skill-autopr.ts',
    'hooks/hook-skill-telemetry': 'src/hooks/hook-skill-telemetry.ts',
    'hooks/hook-context-status': 'src/hooks/hook-context-status.ts',
    'hooks/hook-policy-check': 'src/hooks/hook-policy-check.ts',
    'hooks/hook-policy-check-mcp': 'src/hooks/hook-policy-check-mcp.ts',
    'hooks/hook-env-write-guard': 'src/hooks/hook-env-write-guard.ts',
    'hooks/hook-agent-task-event': 'src/hooks/hook-agent-task-event.ts',
    'hooks/hook-blocked-auto-rotate': 'src/hooks/hook-blocked-auto-rotate.ts',
  },
  format: ['cjs'],
  target: 'node20',
  clean: true,
  splitting: false,
  sourcemap: true,
  dts: false,
  shims: true,
  banner: {
    js: '#!/usr/bin/env node',
  },
  external: ['node-pty'],
});
