#!/usr/bin/env bash
# install-service.sh — Install the linkedin-poster systemd service for one user.
#
# Usage:
#   sudo ./deploy/install-service.sh --user greg --sender-uuid <supabase-auth-uuid> [--port 3100] [--sender-name "Greg Harned"] [--sender-linkedin-id gregoryharned]
#
# What it does:
#   1. Copies the template unit to /etc/systemd/system/
#   2. Creates /etc/linkedin-poster/<user>.env with per-user config
#   3. Creates /var/lib/linkedin-poster/profiles/<user>/ (for Chrome profile)
#   4. Enables and starts linkedin-poster@<user>

set -euo pipefail

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
USER_ID=""
SENDER_UUID=""
PORT="3100"
SENDER_NAME=""
SENDER_LINKEDIN_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)               USER_ID="$2";           shift 2 ;;
    --sender-uuid)        SENDER_UUID="$2";        shift 2 ;;
    --port)               PORT="$2";               shift 2 ;;
    --sender-name)        SENDER_NAME="$2";        shift 2 ;;
    --sender-linkedin-id) SENDER_LINKEDIN_ID="$2"; shift 2 ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

if [[ -z "$USER_ID" ]]; then
  echo "Error: --user <user_id> is required"
  exit 1
fi
if [[ -z "$SENDER_UUID" ]]; then
  echo "Error: --sender-uuid <supabase-auth-uuid> is required"
  echo "  Find it: SELECT id FROM auth.users WHERE email = 'user@example.com';"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="linkedin-poster@${USER_ID}"
UNIT_FILE="/etc/systemd/system/linkedin-poster@.service"
CONF_DIR="/etc/linkedin-poster"
PROFILE_DIR="/var/lib/linkedin-poster/profiles/${USER_ID}"

echo "=== Installing linkedin-poster for user: ${USER_ID} ==="

# ---------------------------------------------------------------------------
# 1. Install systemd unit template
# ---------------------------------------------------------------------------
echo "[1/5] Installing systemd unit template -> ${UNIT_FILE}"
cp "${SCRIPT_DIR}/linkedin-poster@.service" "${UNIT_FILE}"
chmod 644 "${UNIT_FILE}"

# ---------------------------------------------------------------------------
# 2. Create per-user env file
# ---------------------------------------------------------------------------
echo "[2/5] Writing per-user env: ${CONF_DIR}/${USER_ID}.env"
mkdir -p "${CONF_DIR}"
chmod 755 "${CONF_DIR}"

ENV_FILE="${CONF_DIR}/${USER_ID}.env"
cat > "${ENV_FILE}" <<EOF
# linkedin-poster per-user config — ${USER_ID}
# Generated by install-service.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
USER_ID=${USER_ID}
# SENDER_UUID: Supabase auth.users UUID for this LinkedIn account.
# Used for sender_id / requested_by filters (UUID columns — NOT a string handle).
SENDER_UUID=${SENDER_UUID}
PORT=${PORT}
PROFILE_DIR=${PROFILE_DIR}
SENDER_NAME=${SENDER_NAME}
SENDER_LINKEDIN_ID=${SENDER_LINKEDIN_ID}
EOF
chmod 640 "${ENV_FILE}"
echo "   -> ${ENV_FILE}"

# ---------------------------------------------------------------------------
# 3. Ensure shared.env exists (Supabase credentials)
# ---------------------------------------------------------------------------
SHARED_ENV="${CONF_DIR}/shared.env"
if [[ ! -f "${SHARED_ENV}" ]]; then
  echo "[3/5] Creating shared.env template (fill in credentials):"
  cat > "${SHARED_ENV}" <<EOF
# Supabase credentials — shared across all linkedin-poster instances
SUPABASE_URL=https://yyizocyaehmqrottmnaz.supabase.co
SUPABASE_KEY=your-service-role-key-here
EOF
  chmod 640 "${SHARED_ENV}"
  echo "   -> ${SHARED_ENV} (FILL IN SUPABASE_KEY before starting)"
else
  echo "[3/5] Shared env already exists: ${SHARED_ENV}"
fi

# ---------------------------------------------------------------------------
# 4. Create Chrome profile directory
# ---------------------------------------------------------------------------
echo "[4/5] Creating profile dir: ${PROFILE_DIR}"
mkdir -p "${PROFILE_DIR}"
chmod 700 "${PROFILE_DIR}"
# Ensure the cortextos user owns it (service runs as cortextos)
chown cortextos:cortextos "${PROFILE_DIR}" 2>/dev/null || true

# Ensure parent dir also owned
chown cortextos:cortextos /var/lib/linkedin-poster/profiles/ 2>/dev/null || true
chown cortextos:cortextos /var/lib/linkedin-poster/ 2>/dev/null || true

# ---------------------------------------------------------------------------
# 5. Enable and start the service
# ---------------------------------------------------------------------------
echo "[5/5] Enabling and starting ${SERVICE_NAME}"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl start "${SERVICE_NAME}"

echo ""
echo "=== Done! ==="
echo "Service: ${SERVICE_NAME}"
echo "Status:  systemctl status ${SERVICE_NAME}"
echo "Logs:    journalctl -u ${SERVICE_NAME} -f"
echo ""
echo "Next: seed the Chrome profile with the login CLI, then verify:"
echo "  curl http://127.0.0.1:${PORT}/health"
