-- 0002_spawn_leases.sql
-- Phase 2e (Δ1) — spawn_leases table.
--
-- Replaces the file-based per-agent lock in the daemon spawn path.
-- The lease key is (project_id, agent_name) — project_id NULL-tolerant
-- per B1 conventions (NULL means "fleet-wide / unscoped" lease, matching
-- pre-multi-project behavior). Holder is identified by an opaque holder_id
-- (UUID) chosen by the caller; the same holder may re-acquire and extend
-- their own lease (idempotent refresh), but a different holder must wait
-- for expiry.
--
-- Polling rather than pg_notify per top-g signoff 2026-05-17 — re-evaluate
-- after we have lease metrics; add notify only if poll thrash measures bad.

create table if not exists cortextos.spawn_leases (
  -- Surrogate id for FK targets / row-level operations. The semantic key
  -- is (project_id, agent_name) — see the UNIQUE NULLS NOT DISTINCT below.
  id            bigserial primary key,

  -- Composite uniqueness: project scope + agent name. project_id is
  -- NULL-tolerant (B1 convention) — NULL means "unscoped/fleet-wide".
  -- NULLS NOT DISTINCT (PG15+) makes two NULL slots collide so the
  -- unscoped lease per agent is also mutually exclusive.
  project_id    text,
  agent_name    text not null,

  -- Opaque holder identifier — typically a UUID generated by the daemon at
  -- claim time. Caller-owned; we do not interpret it.
  holder_id     text not null,

  -- ISO 8601 timestamps. acquired_at is set on first acquire (and rewritten
  -- on re-acquire by the same holder so the lease behaves as a sliding
  -- window). expires_at is acquired_at + ttl_seconds.
  acquired_at   timestamptz not null default now(),
  expires_at    timestamptz not null,

  -- TTL in seconds — recorded for audit/extension math. Defaults to 90s
  -- which matches the existing file-lock heartbeat cadence.
  ttl_seconds   integer not null default 90 check (ttl_seconds > 0),

  -- Optional human-readable reason ("spawn", "restart", "manual-grab") for
  -- observability. Not used for matching.
  reason        text,

  -- Audit metadata.
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- Composite uniqueness. NULLS NOT DISTINCT (PG15+) makes (NULL, 'foo')
  -- collide with (NULL, 'foo') so the unscoped slot per agent_name is
  -- mutually exclusive — required for the unscoped-fleet lease semantics.
  -- We cannot use this combination as a PRIMARY KEY because PK columns are
  -- implicitly NOT NULL; hence the surrogate `id` bigserial above.
  unique nulls not distinct (project_id, agent_name)
);

comment on table cortextos.spawn_leases is
  'Per-(project, agent) lease for daemon spawn coordination. Replaces '
  'the file-based per-agent lock. NULL project_id partition = unscoped/'
  'fleet-wide lease. Polling-based, no pg_notify in phase 2e.';

comment on column cortextos.spawn_leases.project_id is
  'NULL-tolerant project scope. NULL = unscoped/fleet-wide. NOT a wildcard.';

comment on column cortextos.spawn_leases.holder_id is
  'Opaque caller-chosen id (typically UUID). Same holder may re-acquire '
  'to slide the expires_at window; different holder must wait for expiry.';

-- Lookup index for expiry sweeps and "list leases for agent X across projects"
-- diagnostics. The primary key already covers (project_id, agent_name) for
-- exact-match acquire.
create index if not exists spawn_leases_expires_idx
  on cortextos.spawn_leases (expires_at);

create index if not exists spawn_leases_agent_idx
  on cortextos.spawn_leases (agent_name);

-- updated_at auto-refresh trigger so re-acquire shows a fresh updated_at.
create or replace function cortextos.spawn_leases_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists spawn_leases_set_updated_at on cortextos.spawn_leases;
create trigger spawn_leases_set_updated_at
  before update on cortextos.spawn_leases
  for each row execute function cortextos.spawn_leases_set_updated_at();
